---
abstract: 'use C<Tickit> with C<IO::Async>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::HexString: 0
  Test::More: 0
  Test::Refcount: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Async
provides:
  Tickit::Async:
    file: lib/Tickit/Async.pm
    version: 0.12
requires:
  IO::Async: 0.47
  IO::Async::Notifier: 0.43
  IO::Async::Stream: 0.34
  IO::Async::Test: 0
  Tickit: 0.14
resources:
  license: http://dev.perl.org/licenses/
version: 0.12
